version: '3.8'

services:
  rasa-actions:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SERVICE_TYPE=actions
      - PORT=5055
    ports:
      - "5055:5055"

  rasa-core:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SERVICE_TYPE=core
      - PORT=5005
      - ACTION_SERVER_URL=http://rasa-actions:5055/webhook
      - RASA_PRO_LICENSE=${RASA_PRO_LICENSE} # Uncomment if you have a license
    ports:
      - "5005:5005"
    depends_on:
      - rasa-actions
    volumes:
      - ./models:/app/models
